### ISSUE TITLE
People table

### ISSUE THREAD

**Issue by manndave** [OpenGenOrg/rosetta#1]

**Comment by manndave** [comment]
[RM Database Analysis.docx](https://github.com/OpenGenOrg/rosetta/files/2108271/RM.Database.Analysis.docx)

**Comment by kimberlysamar** [comment]
Hi @manndave . While working on familytable, I found out some info on the parentID and spouseID columns for your table that explains how parents and spouses are stored. I am attaching an updated file with my additions. If you want this done a different way, just let me know. I'm still chugging on familytable.
[RM.Database.Analysis.docx](https://github.com/OpenGenOrg/rosetta/files/2193475/RM.Database.Analysis.docx)

**Comment by manndave** [comment]
@kimberlysamar - this is perfect!  Exactly how I hoped things would work out .  There are naturally going to be relationships between tables and sussing out what those are is going to be the hard part of this project so I was hoping that it would naturally evolve as each table build upon what has been done already.
I still need to digest what you found, but it looks good.  I'm keeping a "master" copy of the tables doc so I'll update that once I've grokked what you found.

:-)

**Comment by kimberlysamar** [comment]
Thanks @manndave ! I was wondering how you wanted to assemble the master. This sounds like a good plan :-)

**Comment by manndave** [comment]
Looks good, moved to master copy.
